# Spec file for deploying multiple pods of my-app
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: sample-app
      labels:
        name: sample-app
        tier: frontend
    spec:
      volumes:
        - name: spring-cfg
          secret:
            secretName: sample-app-cfg
      containers:
        - name: application
          image: nicus/k8s-sample_application:0.1
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: spring-cfg
              mountPath: "/etc/spring"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: "http"
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: "http"
            initialDelaySeconds: 30
            timeoutSeconds: 1
