apiVersion: v1
kind: Service
metadata:
  name: h2server
  labels:
    app: sample-app
    tier: backed
spec:
  ports:
    - port: 1521
      protocol: TCP
      targetPort: 1521
  selector:
    name: h2server
