apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: h2server
spec:
  replicas: 1
  template:
    metadata:
      name: h2server
      labels:
        name: h2server
        tier: backend
    spec:
      volumes:
        - name: h2-data
          awsElasticBlockStore:
            volumeID: "<VOLUME-ID>" # TODO REPLACE WITH ACTUAL VOLUME ID
            fsType: ext4
      containers:
        - name: h2
          image: "<DOCKERHUB-ACCOUNT>/k8s-sample_h2db:0.1" # TODO REPLACE WITH YOUR DOCKERHUB ACCOUNT
          volumeMounts:
          - mountPath: /var/h2-data
            name: h2-data
          ports:
            - containerPort: 1521
              name: h2tcp
            - containerPort: 81
              name: h2ui
          readinessProbe: # Not a proper readiness check, but H2 has no proper API
            httpGet:
              path: /
              port: 81
            initialDelaySeconds: 5
            timeoutSeconds: 1
